# Generated by Django 2.2.2 on 2019-06-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.TextField(blank=True, null=True)),
                ('carrier', models.FloatField(blank=True, null=True)),
                ('location_no', models.FloatField(blank=True, null=True)),
                ('mcmu', models.FloatField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('customer_code', models.FloatField(blank=True, null=True, unique=True)),
                ('zone', models.TextField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('rtkm', models.FloatField(blank=True, null=True)),
                ('klkm', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('load', models.FloatField(blank=True, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
